image: node:latest

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - vite build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
    - master
